export const SET_LOGINSTATE = 'SET_LOGINSTATE'
export const SET_TITLESNAME = 'SET_TITLESNAME'
export const SET_CHECKEDSTATE = 'SET_CHECKEDSTATE'
export const CHANGE_CHECKEDSTATE = 'CHANGE_CHECKEDSTATE'
